apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient-container
        image: 23mis0614/patient-system:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080